version: '3'
services:
    server:
        container_name: stylify-rollupjs-example
        image: node:14
        working_dir: /var/www/html
        volumes:
            - ./.:/var/www/html:delegated
        tty: true
