version: '3'
services:
    server:
        container_name: stylify-reactjs-example
        image: node:14
        working_dir: /var/www/html
        volumes:
            - ./.:/var/www/html:delegated
        ports:
            - 3000:3000
        tty: true
