version: '3'
services:
    server:
        container_name: stylify-vitejs-example
        image: node:14
        working_dir: /var/www/html
        ports:
            - 0.0.0.0:3000:3000
        volumes:
            - ./.:/var/www/html:delegated
        tty: true
